# Directory Settings
source: ./src
destination: ./build/deploy
plugins: ./src/_plugins

# Site Specific Settings
timezone: America/New_York
permalink: /:title
url: http://www.neverstopbuilding.com
default_page_image: https://lh5.googleusercontent.com/-N-zIzELpE4Q/Umngjlc4rLI/AAAAAAAAJCk/EnHYREZvgLI/w1117-h316-no/tattoo.png
default_home_image: https://lh5.googleusercontent.com/-75568V798uI/UhmjUBPD5uI/AAAAAAAAIWA/I-t9QxUhkdA/w1002-h668-no/2013-08-23-115546.jpg
title: Never Stop Building
description: "Learn about high quality software engineering, code craftsmanship, productivity, electronics and inventions. By Jason Fox, renaissance man and builder."

# Syndication Settings
feed: http://feeds.feedburner.com/neverstopbuilding/TGMp

#Builder Information
author: Jason Fox
email: mailto:jasonrobertfox@gmail.com
twitter: https://twitter.com/jasonrobertfox
twitter_username: jasonrobertfox
youtube: http://www.youtube.com/user/POtrippleX
github: https://github.com/jasonrobertfox
google_plus: https://plus.google.com/109774408645971700391
instagram: http://instagram.com/jasonrobertfox
from: "Washington, DC, USA"

# Plugin Settings
markdown: redcarpet
pygments: true

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: nil
  gzip: true

sitemap:
  branch: master
